### ISSUE TITLE
pocket-id and pocker-id-portal working example

### ISSUE THREAD

**Issue by yw5ueq** [kmendell/pocket-id-portal#65]
Hey, first of all thank you for your work on amazing project. I am trying to setup pocket-id-portal with pocket-id. What is the correct callback URL to put into OIDC client section on pocket-id?

Here's the pocket-id-portal docker compose file.

```yaml
services:

  portal:
    container_name: pocket-id-portal
    image: ghcr.io/pocket-id/pocket-id-portal:v1.4.1
    ports:
      - "3000:3000"
    restart: unless-stopped
    volumes:
      - ./config:/app/data
    environment:
      PUBLIC_OIDC_ISSUER: "https://id.example.com"
      PUBLIC_OIDC_CLIENT_ID: "<redacted>"
      OIDC_CLIENT_SECRET: "<redacted>"
      PUBLIC_OIDC_SCOPES: "openid profile email"
      POCKET_ID_API_KEY: "<redacted>"
      PUBLIC_APP_URL: "http://192.168.56.11:3000"
```

Pocket ID client setup:
<img width="1296" alt="Image" src="https://github.com/user-attachments/assets/01098f72-4b92-4669-bbf1-506c9954d2a8" />

I tried using `http://192.168.56.11:3000/callback` but I am getting redirected back to login.
